# Generated by Django 4.0.2 on 2022-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureimage',
            name='height',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='natureimage',
            name='width',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='natureimage',
            name='comment',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AlterField(
            model_name='natureimage',
            name='url',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
