# Generated by Django 4.0.2 on 2022-02-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_natureimage_height_natureimage_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natureimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='natureimage',
            name='width',
        ),
    ]
