# Generated by Django 4.0.2 on 2022-02-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_natureimage_height_remove_natureimage_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='natureimage',
            name='height',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='natureimage',
            name='width',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
